### ISSUE TITLE
Spectator Mode

### ISSUE THREAD

**Issue by SuperKali** [GamakCZ/SkyWars#18]
## Name

I have good idea, is good adding spectator mode, and one compass on inventory that if touch open gui with three options, the first option is play again in another maps available, second option that can see all list of players in the game alive also can teleport from you, final option left the map and return on the lobby
### Description:

__Paste issue description here.__

### How to reproduce?

1) ...
2) ...

### Server version:

- This server is running ... 「...」 implementing API version ... for Minecraft: ... ... (protocol version ...)

**Comment by mote166** [comment]
good idea but if ur going to implement it make it optional

**Comment by GamakCZ** [comment]
Closed due to inactivity.
