### ISSUE TITLE
arena not reset fine

### ISSUE THREAD

**Issue by SuperKali** [GamakCZ/SkyWars#21]
### Description:

__Paste issue description here.__

### How to reproduce?

1) ...
2) ...

### Server version:

- This server is running ... 「...」 implementing API version ... for Minecraft: ... ... (protocol version ...)

**Comment by SuperKali** [comment]
![minecraft 26_05_2018 16_55_27](https://user-images.githubusercontent.com/19473898/40577427-b19a629c-6105-11e8-9754-79502a18a969.png)

**Comment by SuperKali** [comment]
i have changed only text join, quit ecc

**Comment by mote166** [comment]
@SuperKali u know , putting the errors can actually help the developer find the issue and fix it faster , i suggest u set debug mode to 2 in pocketmine.yml when testing this plugin so the full error can appear in the console .

**Comment by SuperKali** [comment]
but, in console not have errors

**Comment by mote166** [comment]
i just tried to reproduce the issue but the plugin is working just fine , no errors using PMMP's dev#1001 release.

**Comment by GamakCZ** [comment]
Please, edit the information in the issue label and use MY plugin.

**Comment by SuperKali** [comment]
when I turn off the server is the game is not over remain the blocks placed of the old game

**Comment by GamakCZ** [comment]
![arena not reset fine issue 21 gamakcz_skywars - google chrome 27 05 2018 11_41_23](https://user-images.githubusercontent.com/17053298/40584567-36b2e9ca-61a3-11e8-9216-1ff21c12fae7.png)

**Comment by LewBr** [comment]
Hey, @GamakCZ did you have Twitter or something to speak? I will do some things for this plugin with you :)

**Comment by GamakCZ** [comment]
Discord

**Comment by LewBr** [comment]
can you give me a link? or username

**Comment by GamakCZ** [comment]
https://discord.gg/uwBf2jS

**Comment by GamakCZ** [comment]
Closed due to inactivity.
