### ISSUE TITLE
Arenas do not save

### ISSUE THREAD

**Issue by ItzJNTZ** [GamakCZ/SkyWars#25]
So basically I created set up an arena with spawns, level etc.. and used savelevel after exiting the setup.
Here everything works perfectly but...
Every time I restart the server it is like the arena never existed and i have to create it and set it up again.

**Comment by dostaljsembanalemamnovyucet** [comment]
Windows/Linux?

**Comment by ItzJNTZ** [comment]
I think my host (roxserver) runs it on windows

**Comment by dostaljsembanalemamnovyucet** [comment]
Your php may not have access to config of the plugin, contact your host

**Comment by GamakCZ** [comment]
We need more information.

**Comment by Hallis1221** [comment]
Same issue, running my self on windows no reason it suldent have acsess, same issue with the 1vs1 plugin
