### ISSUE TITLE
Can You Update To 3.0.0

### ISSUE THREAD

**Issue by DeadOnBushPH** [GamakCZ/SkyWars#28]

**Comment by GamakCZ** [comment]
yes, I can 👍

**Comment by DeadOnBushPH** [comment]
I will test it now

**Comment by DeadOnBushPH** [comment]
Bug is some players can't place blocks or open the chest and some players can't PvP when the game starting

**Comment by treehousemc1** [comment]
You sure? It's working fine for me. Try use newer version.

**Comment by DeadOnBushPH** [comment]
OK treehouse thx

**Comment by Flipax** [comment]
Ay Developers, I've tested this on many servers, but the arena doesn't get saved after we restart the server. I've tried the savelevel command. It still doesn't work. Like the signs are still there but it doesn't work, Any fix for this issue?
