### ISSUE TITLE
This is a great plugin, but...

### ISSUE THREAD

**Issue by nikoskon2003** [GamakCZ/SkyWars#33]
Ok i know this is not an issue.
This is a great plugin, but it lacks the ability to customise ALOT of things!
This is a list that i made:
1) Messages.
2) When the player wins (what commands to do).
3) Chest contents.
4) Join sign contents.
5) time (until game starts, until game ends).
6) Minimum players until game starts. 

Adding these (or some of them) features, will make this plugin one of the best, if not the best, skywars plugin for pocketmine!

**Comment by GamakCZ** [comment]
Here is the link for my SkyWars PRO plugin, if you want it, you can buy it and get most of the new features.
