### ISSUE TITLE
Arenas are gone when PocketMine server restarts

### ISSUE THREAD

**Issue by SRijn1973** [GamakCZ/SkyWars#39]
## Name
Arenas are gone when PocketMine server restarts

### Description:
Each time my server restarts all the arenas are gone. When calling `/sw arenas`, nothing shows up. The Joinsigns are still visible but they don't work.

### How to reproduce?

1) Restart Server
2) Call `/sw arenas`
3) No arenas show

### Server version:
PocketMine-MP 3.3.0

**Comment by GamakCZ** [comment]
Is arena enabled?

**Comment by SRijn1973** [comment]
Not yet, I could try that as a last resort. I just noticed that the **saves** folder contains .zip files as expected but the **arenas** folder is always empty. Is that how it is supposed to be?

**Comment by GamakCZ** [comment]
there can be problem with changed plugin's data folder (now it is on plugin_data)

**Comment by SRijn1973** [comment]
That can be a problem, the current server folder is named **plugins**. Should I remove the plugin from the **plugin** folder and move it to the **plugin_data** folder?

**Comment by GamakCZ** [comment]
no, only test plugin on empty server (http://server.pro)

**Comment by SRijn1973** [comment]
Ok, will do that. No time to do it in the coming days however. I wil let you know if this works next week. Thanks so far.

**Comment by llronaldoll** [comment]
same problem!!

**Comment by SRijn1973** [comment]
Reinstalling server (with complete wipe) still does not help :-( I notice that the plugins/SkyWars/Arenas folder is always emtpy. The plugins/SkyWars/Saves folder does contain .zip files. Does that tell you anything?

**Comment by SRijn1973** [comment]
I have contacted the server supportdesk. Waiting for an answer.

**Comment by Flipax** [comment]
What's the use of this plugin if it can't save the arenas after restart. Plus it isn't possible for every Server host to make it 100% online. There's no usage of this plugin if we have to use it on a sever.pro host.

**Comment by GamakCZ** [comment]
unconfirmed
