### ISSUE TITLE
Sign doesnt really work, hit or miss

### ISSUE THREAD

**Issue by xXRyzen** [GamakCZ/SkyWars#46]
### Description: When tapping on SW join sign it doesnt TP players to arena, have to tap many times and only "sometimes" it TP's player to arena.

__Paste issue description here.__

### How to reproduce?

1) ...Set up Skywars arena
2) ...Add Join Sign
3)...Tap sign
4)...Nothing

### Server version:

--- + --------------- + ---
2019-01-22 [23:51:04] [Server thread/INFO]: This server is running PocketMine-MP 3.5.3 for Minecraft: Bedrock Edition v1.8.0 (protocol version 313)

**Comment by GamakCZ** [comment]
Is arena enabled?

**Comment by FienixEC** [comment]
Yes everything works except for the sign. Funny enough. I found that the tap activation is located on the left narrow side part of the sign. So tappung the left edge of the sig  does tp players lol

**Comment by GamakCZ** [comment]
Is sign formated?

**Comment by FienixEC** [comment]
Yes its formatted correctly. displays arena info correct. but tapping front of sign does nothing tapping side left edge sends player to SW arena
