### ISSUE TITLE
SkyWars-Rewards doesn't detect SkyWars_v1.1.1

### ISSUE THREAD

**Issue by CryptoKey98** [GamakCZ/SkyWars#48]
`[Server thread/CRITICAL]: pocketmine\plugin\PluginException: "SkyWars plugin was not found!" (EXCEPTION) in "plugins/SkyWars-Reward.phar/src/skywars/SWReward" at line 40`

**Comment by GamakCZ** [comment]
Have you enabled SkyWars plugin?

**Comment by GamakCZ** [comment]
To run sw reward you must run SkyWars (from poggit) and SkyWars-Reward too

**Comment by CryptoKey98** [comment]
I have both SkyWars and SkyWars-Reward in my plugin's folder and what do you mean enable? There's no config file in plugin_data,,,

**Comment by piyushbest** [comment]
Remove all old plugin then try

**Comment by CryptoKey98** [comment]
@piyushbest I have done that. Same error.

**Comment by GamakCZ** [comment]
sw reward must be compatible with skywars plugin (sw reward and sw versions must be same) so use skywars v1.1.0; insteadof v1.1.1
