### ISSUE TITLE
[Issue] Level Command

### ISSUE THREAD

**Issue by DrXerious** [GamakCZ/SkyWars#49]
## Name
Using Level <Name of Arena> says "Level <Name of Arena> does not found!"

### Description:
I was following the tutorial and it seems like i was stuck where you do
/sw set <Arena> then level <arena>

### Server version:

2019-03-11 [16:40:31] [Server thread/INFO]: This server is running PocketMine-MP version 3.6.5

**Comment by GamakCZ** [comment]
you must type existing level
