### ISSUE TITLE
Level <arena name> is not generated yet! Try /mw create for generate level

### ISSUE THREAD

**Issue by starchx** [GamakCZ/SkyWars#50]
### Description:

I am following the video: https://www.youtube.com/watch?v=3tbhWPUFe1c
and up to joinsign, which completed fine. It failed at: /mw tp <arena name>

The error says: Level <arena name> is not generated yet! Try /mw create for generate level

### How to reproduce?
1) /sw create triple
2) /sw set triple
3) slots 12
4) joinsign
5) /mw tp triple
Level triple is not generated yet! Try /mw create for generate level

### Server version:

Server: PMMP 3.7.0
SkyWars plugins tried:
  https://poggit.pmmp.io/r/38797/SkyWars.phar
  https://poggit.pmmp.io/r/49877/SkyWars.phar
MultiWorld plugin: 1.5.0

**Comment by GamakCZ** [comment]
MultiWorld is world management plugin, so you can manage with worlds using it (generate new one, teleport players behind it, ...). In my video I've used this plugin to teleport between worlds. SkyWars plugin depends one world for one arena, for example in my video I used some map downloaded from youtube... So you must first generate or download level and then set arena in it.
