### ISSUE TITLE
If i restart my server the arena not save 

### ISSUE THREAD

**Issue by derrenrafa** [GamakCZ/SkyWars#53]
### Description:

__Paste issue description here.__

### How to reproduce?

1) ...if i restart my server the arena Is clear to 0
2) ...plss help

### Server version:
Api : 3.0.0 4.0.0 update
Protokol 4.3.5

**Comment by derrenrafa** [comment]
Help plss

**Comment by GamakCZ** [comment]
reproduced on TheBridge minigame at HyperLands server

**Comment by GamakCZ** [comment]
I'll try to fix this error.

**Comment by derrenrafa** [comment]
Thanks but plss tell me again if you done fix it

**Comment by derrenrafa** [comment]
My server is closed for waiting this skywars plugins

**Comment by derrenrafa** [comment]
But thank you!!

**Comment by GamakCZ** [comment]
FINALLY FIXED
