### ISSUE TITLE
Error savelevel

### ISSUE THREAD

**Issue by BogdanMakarchuk** [GamakCZ/SkyWars#57]
### Description:
1. /sw set arena
2. settings -> savelevel = error
13:14:17] [Server thread/CRITICAL]: Error: "Call to a member function saveMap() on null" (EXCEPTION) in "plugins/SkyWars/src/vixikhd/skywars/SkyWars" at line 149

### Server version:
PMMP 1.12.1 last bild (stable)

**Comment by piyushbest** [comment]
Pls see #56

**Comment by piyushbest** [comment]
Also first enable arena then do savelevel
