### ISSUE TITLE
World Error

### ISSUE THREAD

**Issue by Tezi5** [GamakCZ/SkyWars#64]
Hello,
I am using the latest downloaded version directly from the repository. I encounter this error while performing the "savelevel" command.

Error: "Call to a member function saveMap() on null" (EXCEPTION) in "plugins/SkyWars/src/vixikhd/skywars/SkyWars" at line 150

**Comment by GamakCZ** [comment]
Level is now saved automatically when arena is enabled. However thank you for report.
