### ISSUE TITLE
Paid version

### ISSUE THREAD

**Issue by mcpedudes** [GamakCZ/SkyWars#65]
I purchased the paid version and never got it ;_; I can prove if you msg me privately somewhere, I'd rather not show the payments here....

**Comment by GamakCZ** [comment]
I'm really sorry for problems. I'm still working on the website.

**Comment by GamakCZ** [comment]
I've send link to your email.

All the bugs please submit [here](https://github.com/GamakCZ/SkyWars-Pro/issues)
