### ISSUE TITLE
please complete eggwars plugin

### ISSUE THREAD

**Issue by XFIREGANER** [GamakCZ/SkyWars#9]

**Comment by XFIREGANER** [comment]
make generators,shop,and more...

**Comment by HeJuKa** [comment]
It is complete!

**Comment by XFIREGANER** [comment]
What!! itsn't Completed yet! test plugin

**Comment by XFIREGANER** [comment]
how to make generator signs and the villager isn't Spawn

**Comment by HeJuKa** [comment]
Villager You must Spawn With Egg,and Generator With sign.

**Comment by XFIREGANER** [comment]
How write for me all the commands to make arena plz.

**Comment by GamakCZ** [comment]
Invalid
